version: '3.8'

services:
  app:
    build: .
    container_name: anki_bot
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: anki_postgres
    restart: always
    environment:
      POSTGRES_DB: anki
      POSTGRES_USER: anki_user
      POSTGRES_PASSWORD: anki_pass
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: anki_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
